In [242]:
%load_ext autoreload

%autoreload 2
from align import *
from typing import Tuple
import numpy as np

The autoreload extension is already loaded. To reload it, use:
  %reload_ext autoreload


In [28]:
!ls substitution_matrices

BLOSUM50.mat BLOSUM62.mat PAM100.mat   PAM250.mat


In [261]:
def _get_next_cell(self, i,j):
    
    """Returns coordinates of next cell to go to in traceback according to move encoded in traceback matrix"""
    
    move = self._traceback_matrix[i,j]
    
    #move diagonally
    if move == 0:
        return (i-1, j-1)
    #move left
    if move == 1:
        return (i, j-1)
    #move up
    if move == 2:
        return (i-1, j)

In [262]:
seqA, _ = read_fasta("./data/test_seq3.fa")
seqB, _ = read_fasta("./data/test_seq4.fa")

In [263]:
t = NeedlemanWunsch(sub_matrix_file='substitution_matrices/BLOSUM62.mat', gap_open=-10, gap_extend=-1)
sub_matrix = t.sub_dict
sub_dict = t.sub_dict

gap_open = -10
gap_extend = -1

In [264]:
#initialize matrices

matrix_dims = (len(seqA)+1, len(seqB)+1)
alignment_matrix = np.full(matrix_dims, -np.inf)
A_gap_matrix = np.full(matrix_dims, -np.inf)
B_gap_matrix = np.full(matrix_dims, -np.inf)
traceback_matrix = np.full(matrix_dims, -np.inf)

alignment_matrix[0,0] = 0

traceback_matrix[1:,0] = 1
traceback_matrix[0,1:] = 2 
traceback_matrix[0,0] = 0

for i in range(matrix_dims[0]): 
    if i == 0:
        A_gap_matrix[i, 0] = gap_open
    else:
        A_gap_matrix[i, 0] = gap_extend+A_gap_matrix[i-1,0]
    
for j in range(matrix_dims[1]):   
    if j == 0:
        B_gap_matrix[0, j] = gap_open
    else:
        B_gap_matrix[0, j] = gap_extend+B_gap_matrix[0,j-1]
        


In [266]:
alignment_matrix

array([[  0., -inf, -inf, -inf],
       [-inf,   5., -11., -13.],
       [-inf, -12.,   4.,  -8.],
       [-inf, -12.,  -1.,   5.],
       [-inf, -14.,  -6.,   4.]])

In [267]:
traceback_matrix

array([[0., 2., 2., 2.],
       [1., 0., 1., 1.],
       [1., 2., 0., 1.],
       [1., 2., 0., 0.],
       [1., 2., 0., 0.]])

In [268]:
len(seqA), len(seqB)

(4, 3)

In [269]:
matrix_dims

(5, 4)

In [212]:
alignment_matrix

array([[  0., -inf, -inf, -inf, -inf, -inf, -inf, -inf, -inf, -inf, -inf],
       [-inf,   5., -12., -11., -15., -14., -13., -15., -18., -19., -21.],
       [-inf, -11.,   4.,  -8.,  -7.,  -3., -11., -13., -10., -11., -14.],
       [-inf, -10.,  -7.,   5., -10.,  -9.,   1.,  -8., -13., -12., -14.],
       [-inf, -12.,  -8.,  -4.,   2.,  -9.,  -5.,   5., -11., -13., -14.],
       [-inf, -15.,  -9., -11.,  -4.,   3., -11.,  -8.,  10.,  -1.,  -9.],
       [-inf, -17., -11., -12.,   1.,  -4.,   0., -11.,  -6.,  10.,  -3.],
       [-inf, -18., -11., -12., -10.,   0.,  -7.,  -3.,  -9.,  -3.,  17.]])

In [206]:
print("MAVHQLIRRP")

print("M---QLIRHP")

MAVHQLIRRP
M---QLIRHP


In [205]:
print(seqA_algn)
print(seqB_algn)

PHRILQ---M
PRRILQHVAM


In [61]:
len(seqA), len(seqB)

(10, 7)

In [63]:
seqA, seqB

('MAVHQLIRRP', 'MQLIRHP')

In [68]:
seqA

'MAVHQLIRRP'

In [70]:
len(seqA), len(seqB), alignment_matrix.shape

(10, 7, (11, 8))